"""
Django settings for oh_holo_django project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_DEV_SECRET_KEY = 'django-insecure-elg+x!t_00%$ncpvc(24$47w4w^wcoq)ir1y26v+weg_imc-0+'
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", _DEV_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to ON so your local Windows dev loop needs no environment variables.
# Containers set DJANGO_DEBUG=0 explicitly.
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

if not DEBUG and SECRET_KEY == _DEV_SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_DEBUG=0 requires DJANGO_SECRET_KEY to be set to a real secret.")

def _env_list(name):
    return [item.strip() for item in os.environ.get(name, "").split(",") if item.strip()]

# Empty is fine in dev (Django auto-allows localhost when DEBUG=True).
# With DEBUG off, list every hostname the site is reached by, e.g. "oh-holo.lan,localhost".
ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS")
# Needed for the admin login over a non-localhost origin. Schemes are required: "http://oh-holo.lan"
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'tracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# In production nothing like `runserver` serves static files for us, so WhiteNoise
# does it from inside the app. In dev, Django's own static handling is used.
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'oh_holo_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oh_holo_django.wsgi.application'
ASGI_APPLICATION = 'oh_holo_django.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [{
                'address': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379'),
                # channels_redis waits up to 5s inside a blocking read for the next message.
                # redis-py 8 gives every socket read a 5s timeout by default, so an idle
                # consumer dies at exactly 5s. Keep this comfortably above 5.
                'socket_timeout': 30,
            }],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# SQLite for local dev; Postgres whenever POSTGRES_HOST is set (containers).
if os.environ.get('POSTGRES_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'ohholo'),
            'USER': os.environ.get('POSTGRES_USER', 'ohholo'),
            'PASSWORD': os.environ['POSTGRES_PASSWORD'],
            'HOST': os.environ['POSTGRES_HOST'],
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# `collectstatic` gathers every app's static files here; WhiteNoise serves them.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    # Compressed (gzip/brotli) but deliberately NOT hashed-filename "Manifest" storage:
    # our templates build image/sound URLs dynamically from database values, and the
    # manifest variant raises an error in production for any file it doesn't know about.
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

HOLODEX_API_KEY = os.environ.get("HOLODEX_API_KEY", "")