# Generated by Django 5.2.17 on 2026-10-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VTuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('youtube_id', models.CharField(blank=True, max_length=64)),
                ('twitch_username', models.CharField(blank=True, max_length=64)),
                ('is_live_youtube', models.BooleanField(default=False)),
                ('is_live_twitch', models.BooleanField(default=False)),
            ],
        ),
    ]
