# Generated by Django 5.2.17 on 2026-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vtuber',
            old_name='youtube_id',
            new_name='youtube_channel_id',
        ),
        migrations.AlterField(
            model_name='vtuber',
            name='slug',
            field=models.SlugField(help_text="Also the CSS theme class, e.g. 'mumei'", unique=True),
        ),
    ]
