# Generated by Django 5.2.17 on 2026-10-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_youtube_id_vtuber_youtube_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtuber',
            name='icon',
            field=models.CharField(blank=True, help_text='Filename inside tracker/static/tracker/images/', max_length=100),
        ),
    ]
