# Generated by Django 5.2.17 on 2026-10-03 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_vtuber_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('twitch', 'Twitch')], max_length=10)),
                ('stream_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('vtuber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='tracker.vtuber')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
