# Generated by Django 5.2.17 on 2026-10-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_streamarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamarchive',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamarchive',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('ended', 'Ended')], default='ended', max_length=10),
        ),
        migrations.AddField(
            model_name='streamarchive',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vtuber',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vtuber',
            name='subscriber_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vtuber',
            name='view_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
