# Generated by Django 5.2.17 on 2026-10-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_streamarchive_scheduled_at_streamarchive_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtuber',
            name='alt_icon',
            field=models.CharField(blank=True, help_text='Small variant of icon', max_length=100),
        ),
    ]
