# Generated by Django 5.2.17 on 2026-10-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_vtuber_alt_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtuber',
            name='noise',
            field=models.CharField(blank=True, help_text='Noise when img clicked', max_length=100),
        ),
    ]
